/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DCPD;

import java.awt.Font;
import java.awt.FontFormatException;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Van
 */
public class InformationSection extends javax.swing.JFrame {

    Font ManropeTitle, ManropeUI, Coolvetica;
    public InformationSection() {
        loadFont();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        BackToMenuButton = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Kenneth Omac");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CRD: Information Page");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(ManropeTitle);
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("CJ Destajo");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 160, -1));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(ManropeTitle);
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Kenneth Omac");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 200, -1));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(ManropeTitle);
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Van Maligsa");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 180, -1));

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(ManropeTitle);
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Reygian Mateo");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 210, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(ManropeTitle);
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("John Andrei Lee");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 220, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(Coolvetica);
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Developed By:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        BackToMenuButton.setBackground(new java.awt.Color(0, 102, 102));
        BackToMenuButton.setFont(ManropeUI);
        BackToMenuButton.setForeground(new java.awt.Color(255, 255, 255));
        BackToMenuButton.setText("Back to Menu");
        BackToMenuButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackToMenuButtonActionPerformed(evt);
            }
        });
        getContentPane().add(BackToMenuButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 429, -1, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/NewInformationBG2.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BackToMenuButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackToMenuButtonActionPerformed
       MainMenu MainMenuFrame = new MainMenu ();
       MainMenuFrame.setVisible(true);
       MainMenuFrame.pack();
       MainMenuFrame.setLocationRelativeTo(null);
       this.dispose();
    }//GEN-LAST:event_BackToMenuButtonActionPerformed

    private void loadFont(){
        try { 
            ManropeTitle = Font.createFont(Font.TRUETYPE_FONT, new File("src/resources/fonts/Manrope.ttf")).deriveFont(24f);
            ManropeUI = Font.createFont(Font.TRUETYPE_FONT, new File("src/resources/fonts/Manrope.ttf")).deriveFont(14f);
            Coolvetica = Font.createFont(Font.TRUETYPE_FONT, new File("src/resources/fonts/Coolvetica.otf")).deriveFont(36f);
            
        } catch (FontFormatException ex) {
            Logger.getLogger(Log_InTab.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Log_InTab.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackToMenuButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
