/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package DCPD;

import java.awt.Color;
import java.awt.Font;
import java.awt.FontFormatException;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Van
 */
public class Log_InTab extends javax.swing.JFrame {

    Font ManropeTitle, ManropeUI, Coolvetica, Freshman;
    
    public Log_InTab() {
        loadFont();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always   
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        loginPanel = new javax.swing.JPanel();
        Log_InButton = new javax.swing.JButton();
        PreviousButton = new javax.swing.JButton();
        PasswordHere = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        EmailInput = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        RevealPassword = new javax.swing.JCheckBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CRD: Log-In");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginPanel.setBackground(new java.awt.Color(35, 35, 35));

        Log_InButton.setBackground(new java.awt.Color(0, 153, 153));
        Log_InButton.setFont(ManropeUI);
        Log_InButton.setForeground(new java.awt.Color(255, 255, 255));
        Log_InButton.setText("Log-In");
        Log_InButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Log_InButtonActionPerformed(evt);
            }
        });

        PreviousButton.setBackground(new java.awt.Color(0, 153, 153));
        PreviousButton.setFont(ManropeUI);
        PreviousButton.setForeground(new java.awt.Color(255, 255, 255));
        PreviousButton.setText("Previous");
        PreviousButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreviousButtonActionPerformed(evt);
            }
        });

        PasswordHere.setFont(ManropeUI);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(ManropeUI);
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Password:");

        EmailInput.setFont(ManropeUI);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(ManropeUI);
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("E-mail:");

        jLabel7.setFont(Coolvetica);
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Log-In");

        RevealPassword.setBackground(new java.awt.Color(51, 51, 51));
        RevealPassword.setFont(ManropeUI);
        RevealPassword.setForeground(new java.awt.Color(255, 255, 255));
        RevealPassword.setText("Show Password");
        RevealPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RevealPasswordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(jLabel7))
                    .addGroup(loginPanelLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RevealPassword)
                            .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(loginPanelLayout.createSequentialGroup()
                                    .addComponent(PreviousButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Log_InButton, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel2)
                                .addComponent(jLabel1)
                                .addComponent(EmailInput, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                                .addComponent(PasswordHere)))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel7)
                .addGap(25, 25, 25)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EmailInput, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PasswordHere, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(RevealPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 115, Short.MAX_VALUE)
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(PreviousButton)
                    .addComponent(Log_InButton))
                .addGap(47, 47, 47))
        );

        getContentPane().add(loginPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 500));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/Coat_Of_ArmsDavao.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 290, 290));

        jLabel3.setFont(Freshman);
        jLabel3.setForeground(new java.awt.Color(255, 255, 0));
        jLabel3.setText("C");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 370, -1, -1));

        jLabel4.setFont(Freshman);
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("itzen");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 370, -1, -1));

        jLabel5.setFont(Freshman);
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setText("D");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 430, -1, -1));

        jLabel6.setFont(Freshman);
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("ecords");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 370, -1, -1));

        jLabel9.setFont(Freshman);
        jLabel9.setForeground(new java.awt.Color(255, 51, 0));
        jLabel9.setText("R");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 370, -1, -1));

        jLabel10.setFont(Freshman);
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("atabase");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 430, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons/DavaoSkylinePhotoShopped.png"))); // NOI18N
        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 0, 540, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Button Interaction
    private void Log_InButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Log_InButtonActionPerformed
        
        String PasswordDone = new String (PasswordHere.getPassword());
        String EmailDone = EmailInput.getText();
        
        //Check if there is an input
        if(PasswordDone.isEmpty() && EmailDone.isEmpty())
        {
            PasswordHere.setText("Please Enter your Password");
            PasswordHere.setForeground(Color.RED);
            
            EmailInput.setText("Please Enter your Email");
            EmailInput.setForeground(Color.RED);
        }
        //================
        
        else
        {
            SearchRecords SearchFrame = new SearchRecords();
            SearchFrame.setVisible(true);
            SearchFrame.pack();
            SearchFrame.setLocationRelativeTo(null);
            this.dispose();
        }
        
    }//GEN-LAST:event_Log_InButtonActionPerformed

    
    
    private void PreviousButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreviousButtonActionPerformed
       MainMenu MainMenuFrame = new MainMenu ();
       MainMenuFrame.setVisible(true);
       MainMenuFrame.pack();
       MainMenuFrame.setLocationRelativeTo(null);
       this.dispose();
    }//GEN-LAST:event_PreviousButtonActionPerformed

    private void RevealPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RevealPasswordActionPerformed
        
        if(RevealPassword.isSelected())
        {
            PasswordHere.setEchoChar((char)0);
        }
        
        else
        {
            PasswordHere.setEchoChar('•');
        }
    }//GEN-LAST:event_RevealPasswordActionPerformed
    private void loadFont(){
        try { 
            ManropeTitle = Font.createFont(Font.TRUETYPE_FONT, new File("src/resources/fonts/Manrope.ttf")).deriveFont(18f);
            ManropeUI = Font.createFont(Font.TRUETYPE_FONT, new File("src/resources/fonts/Manrope.ttf")).deriveFont(14f);
            Coolvetica = Font.createFont(Font.TRUETYPE_FONT, new File("src/resources/fonts/Coolvetica.otf")).deriveFont(36f);
            Freshman = Font.createFont(Font.TRUETYPE_FONT, new File("src/resources/fonts/Freshman.ttf")).deriveFont(48f);
            
        } catch (FontFormatException ex) {
            Logger.getLogger(Log_InTab.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Log_InTab.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EmailInput;
    private javax.swing.JButton Log_InButton;
    private javax.swing.JPasswordField PasswordHere;
    private javax.swing.JButton PreviousButton;
    private javax.swing.JCheckBox RevealPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel loginPanel;
    // End of variables declaration//GEN-END:variables
}
